### ISSUE TITLE
missing llama3, ruby recommends to to add base64 to gemspec

### ISSUE THREAD

**Issue by sowcow** [AAlvAAro/ruby-amazon-bedrock#5]

**Comment by AAlvAAro** [comment]
Hi @sowcow thank you for raising this issue, do you have a link where I can see the base64 recommendation to take a look? thanks in advance!

**Comment by sowcow** [comment]
Hi @AAlvAAro, it is what ruby 3.3 warns about
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/

> RubyGems and Bundler warn if users do require the following gems without adding them to Gemfile or gemspec. This is because they will become the bundled gems in the future version of Ruby.

This warning is suppressed if you use bootsnap gem. We recommend to run your application with DISABLE_BOOTSNAP=1 environment variable at least once. This is limitation of this version.

Targeted libraries are:

    abbrev
    base64

**Comment by AAlvAAro** [comment]
thanks @sowcow I'll address this soon

**Comment by ErebusBat** [comment]
@sowcow I have resolved the merge conflicts and explicitly added the `base64` gem to the gemspec to address #5.
